language: java

branches:
  only:
    - master

jdk:
  - oraclejdk8

before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"

addons:
  sonarcloud:
    organization: "jmrozanec-github"
    token:
      secure: "eLi07vooUivdhdChr/4VJUZyGDeQuFSymlwqinpgNPofUOJRRUXqvg1UBggywOJUjwa/6UM08SRc1RPRiqRgY50Ke3NueHbFk+MBIJjyrKo/hPqtUeXkUjtE/Uy64Kju/5n4xAt5FswO1HKJsrQoFAuKo/g46DXJocnYgkWm7xalal3Y3B3rZ5y8M2m5vFHlFoAY2oXbO9tV39XeFMkboLTNB/7brJA1oKlUhv9lZBzsQ22A+oiy9d39QUJbxQntLCeGm1GLnL6ed+5f6gFf+hvv5NgfA1I/ZDsZfbGyNN4dgLYemuXcI4ncMWu2v3F2POqkPGZ8Erc1f1e8rEOW7h3Z/c/KD1of9P+P4FMLM6u+B0GN0BtAq6CP9lxOKwPmzFOrTD0nvUkh4DQnzSPWfsltSxvHRuya+1rbEeYmRiL5Gp+h1ZrJWurLaW8+qSrTva3X9P7dv5g8wYW1BaHrDAyfY7vYjLEfH9QNUNA7FuEUYtFOe1RlVEOb5GECcSpoaPVSeV+TmwiEudbIW/mXrgTocqoKjtZ4Xm0X3Jm4hzCRjpBKL3CM6ojHdra886QQk8EgQypnrlCaS40MeG8smA9xfrq32vltT1IPCuwb1w6zBvg1ms+iRcU+jaK4RZEhHvCJtuG8sLZxRqBawBySMybPxpzms1FGn2RfUS2gNao="
script:
   - > 
     if [ "$TRAVIS_PULL_REQUEST" != "false" ];then 
        mvn org.jacoco:jacoco-maven-plugin:prepare-agent package --settings target/travis/settings.xml -Dsettings.security=target/travis/settings-security.xml -Dmaven.javadoc.skip=true;
        sonar-scanner
     fi
   - > 
     if [ "$TRAVIS_PULL_REQUEST" = "false" ];then 
        mvn org.jacoco:jacoco-maven-plugin:prepare-agent package deploy --settings target/travis/settings.xml -Dsettings.security=target/travis/settings-security.xml -Dmaven.javadoc.skip=true;
        sonar-scanner
     fi

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

after_success:
  - mvn cobertura:cobertura coveralls:cobertura
  - bash <(curl -s https://codecov.io/bash)
